[project]
name = "09-serverless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.8",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
]
